# 用于持续集成(DevOps软件开发实践)
# 1.将构建并测试的过程自动化, 提交代码时, 持续集成服务能够自动触发构建与测试过程, 并反馈结果
# 2.加快开发周期, 同时减少脏代码引入, 而持续集成工具有很多
# 3.常见的包括 Jenkins、Gitlab-CI、Travis CI 和 AppVeyor
# 4.github上项目的持续集成可以选择使用 Travis CI, 也有项目使用 AppVeyor

language: node_js
node_js: 10
script: npm run test
notifications:
  email: false
